nome = input("Entre com seu nome: ")
idade = int(input("Entre com sua idade: "))
peso = float(input("Entre com seu peso: "))
altura = float(input("Entre com sua altura: "))

print("FICHA CADASTRAL:")
print(f"Nome: {nome}")
print(f"Idade: {idade}")
print(f"Peso: {peso}")
print(f"Altura: {altura}")               
